baseURL = "/"
disqusShortname = ""
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "github.com/themefisher/northendlab-hugo"
title = "Commerce Grind"
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 1
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Commerce Grind"
contact_form_action = "#"
copyright = "&copy; 2020 [The Commerce Grind](https://thecommercegrind.com) All Rights Reserved"
description = "This is meta description"
google_analitycs_id = ""
google_tag_manager = ""
home = "Home"
logo = "https://res.cloudinary.com/david-stillson-media/image/upload/c_scale,e_bgremoval,w_196/v1606276001/commerce-grind/1598850390192_1307_logo-01_Cropped_jibwyh.png"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.svg"
title = "Hi, I'm David Stillson. <br> I help people build cool things related to ecommerce"
[params.cta]
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
enable = true
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://gethugothemes.com/shop/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-github"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
